version: "3.9"
services:
  rust:
    build: .
    ports:
      - 28015:28015
      - 28015:28015/udp
      - 28016:28016
      - 28082:28082
      - 28083:28083
    volumes:
      - ./steamcmd:/steamcmd
    command: /bin/bash -c ./start.sh
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
     - .env
    environment:
      - RUST_SERVER_IP: 0.0.0.0
      - RUST_SERVER_PORT: 28015
      - RUST_RCON_WEB: 1
      - RUST_RCON_IP: "0.0.0.0"
      - RUST_RCON_PORT: 28016
      - RUST_RCON_PASSWORD: "12341234"
      - RUST_SERVER_MAXPLAYERS: 100
      - RUST_SERVER_LEVEL: "Procedural Map"
      - RUST_SERVER_SEED: 42069
      - RUST_SERVER_WORLDSIZE: 3500
      - RUST_SERVER_SAVEINTERVAL: 300

volumes:
  steamcmd:

